
# Shared content for Home and Login pages

HOME_CONTENT = {
    'hero_title': "The For You Data Hub",
    'intro': (
        "Welcome to the For You Data Hub. We invite you to experiment with this research tool "
        "and explore data from the For You Project. Read more about the project "
        "<a href='https://www.foryouresearch.net/' target='_blank'>here</a>."
    ),
    
    'intentions_title': "Our intentions with this tool",
    'intentions_text': (
        "We hope that this tool eventually will allow social science and humanities researchers "
        "to analyse complex data from short video platforms. With this tool, we are also exploring the capabilities and limitations of "
        "using Gen AI to support annotation and analysis of video content at scale. You can combine "
        "machine annotations with your own annotations, and work in teams to annotate videos together "
        "and assess your team's inter coder reliability as well as the quality of the machine "
        "based annotations."
    ),
    
    'notes_title': "Important notes",
    'note_1': (
        "Note 1: This tool is VERY experimental and under development. It is not a well-polished "
        "product. Things go wrong and there are several bugs that remain to be fixed. We would "
        "greatly appreciate if you would let us know about broken things you find or suggestions "
        "you may have by sending an email to info@foryouresearch.net. At this stage, we have "
        "tested the tool in a Chrome browser in a Mac OS. We have not tested it in other browsers "
        "or operating systems, so we cannot guarantee that it will work as expected in those "
        "environments."
    ),
    'note_2': (
        "Note 2: Some of the data presented in this tool is generated by AI and may be incorrect, "
        "misleading and even deeply upsetting. For that we apologise and ask for your understanding "
        "while this tool and our research methods are being developed. You cannot use any of the "
        "findings you may generate using this tool in any publication without our explicit "
        "permission."
    ),
    
    'ack_title': "Acknowledgements",
    'ack_text': (
        "This research project is based at QUT's Digital Media Research Centre in Brisbane and at "
        "the University of Sydney. It is supported by a grant from the Australian Research Council "
        "and by the Australian Internet Observatory (AIO). The AIO received investment from the "
        "Australian Research Data Commons through the National Collaborative Infrastructure Strategy "
        "in partnership with a consortium of Australian universities. TikTok is a registered "
        "trademark of Bytedance Ltd. This website is not affiliated with or endorsed by TikTok "
        "or Bytedance Ltd."
    )
}
