#!/usr/bin/env python3
"""Reproduce the cookie-file truncation race and verify the private-copy fix.

Root cause: yt-dlp rewrites its ``cookiefile`` (non-atomic truncate-then-write)
on every ``YoutubeDL`` context exit. When the scraper runs many ``YoutubeDL``
instances concurrently against one shared ``/tmp/<platform>_cookies.txt``, one
thread's save truncates the file while another's construction loads it, and the
loader raises "does not look like a Netscape format cookies file".

This exercises the real ``yt_dlp.cookies.YoutubeDLCookieJar`` load/save cycle:
  * OLD pattern (shared path)  -> demonstrates LoadErrors under concurrency.
  * NEW pattern (private copy) -> zero LoadErrors, canonical file stays valid.
"""

import os
import sys
import tempfile
import threading

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from http.cookiejar import LoadError

from yt_dlp.cookies import YoutubeDLCookieJar

from fyp import scraper_cookies


_VALID_COOKIES = (
    "# Netscape HTTP Cookie File\n"
    "# This file is generated by yt-dlp.  Do not edit.\n\n"
    ".tiktok.com\tTRUE\t/\tTRUE\t9999999999\tsessionid\tdeadbeefcafebabe\n"
    ".tiktok.com\tTRUE\t/\tTRUE\t9999999999\ttt_csrf_token\tabc123\n"
)


def _write_valid(path: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(_VALID_COOKIES)


def _hammer(get_cookiefile, iterations: int, errors: list) -> None:
    """Faithfully mimic one scraper thread: load then save via yt-dlp's jar."""
    for _ in range(iterations):
        path = get_cookiefile()
        try:
            jar = YoutubeDLCookieJar(path)
            jar.load()          # yt-dlp does this at YoutubeDL() construction
            jar.save()          # ...and this on context-manager exit
        except LoadError as e:
            errors.append(str(e))
        except Exception as e:  # noqa: BLE001 - surface anything unexpected
            errors.append(f"{type(e).__name__}: {e}")


def _run(get_cookiefile, n_threads=8, iterations=40) -> list:
    errors: list = []
    threads = [
        threading.Thread(target=_hammer, args=(get_cookiefile, iterations, errors))
        for _ in range(n_threads)
    ]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    return errors


def test_helpers() -> None:
    """Netscape-header validation accepts good files and rejects bad ones."""
    with tempfile.TemporaryDirectory() as d:
        good = os.path.join(d, "good.txt")
        _write_valid(good)
        assert scraper_cookies._looks_like_netscape(good), "valid file rejected"

        empty = os.path.join(d, "empty.txt")
        open(empty, "w").close()
        assert not scraper_cookies._looks_like_netscape(empty), "empty file accepted"

        jsonf = os.path.join(d, "cookies.json")
        with open(jsonf, "w") as f:
            f.write('[{"name": "sessionid"}]\n')
        assert not scraper_cookies._looks_like_netscape(jsonf), "JSON file accepted"

        missing = os.path.join(d, "nope.txt")
        assert not scraper_cookies._looks_like_netscape(missing), "missing file accepted"
    print("PASS: _looks_like_netscape accepts valid, rejects empty/JSON/missing")


def test_race() -> None:
    with tempfile.TemporaryDirectory() as d:
        canonical = os.path.join(d, "tiktok_cookies.txt")
        _write_valid(canonical)

        # OLD behaviour: every thread hands yt-dlp the same shared file.
        old_errors = _run(lambda: canonical)
        print(f"OLD (shared file):  {len(old_errors)} LoadError(s) across threads")
        if old_errors:
            print(f"                    e.g. {old_errors[0]}")

        # Restore a clean canonical file for the new run.
        _write_valid(canonical)

        # NEW behaviour: each call gets a private, disposable copy.
        work_dir = os.path.join(d, "work")

        def get_private():
            # Mirror _private_cookie_copy but into the test's own work dir so we
            # don't touch /tmp during the test.
            os.makedirs(work_dir, exist_ok=True)
            fd, dst = tempfile.mkstemp(prefix="tiktok_", suffix=".txt", dir=work_dir)
            with os.fdopen(fd, "wb") as out, open(canonical, "rb") as f:
                out.write(f.read())
            return dst

        new_errors = _run(get_private)
        print(f"NEW (private copy): {len(new_errors)} LoadError(s) across threads")

        # The canonical file must remain a valid Netscape file after the new run.
        assert scraper_cookies._looks_like_netscape(canonical), \
            "canonical file corrupted under new pattern"
        assert not new_errors, f"private-copy pattern still raced: {new_errors[:3]}"

        # The whole point: the shared pattern was capable of racing (so the fix
        # addresses a real failure), and the private-copy pattern eliminates it.
        assert old_errors, (
            "shared-file pattern did not reproduce the race in this run — "
            "timing-dependent; re-run. The fix is still correct."
        )
    print("PASS: private-copy pattern eliminates the LoadError race")


if __name__ == "__main__":
    test_helpers()
    test_race()
    print("\nAll cookie-race tests passed.")
