##########################################################################################
# Core toml files
##########################################################################################
[core]

config_fn = "config.toml" 
study_defs_fn = "studies.toml"
