# ====================================================================================
# Study parameters: Documentation
# ===================================================================================

######### START_DATE [str]
# yyyy-mm-dd only include events after this date - DEFAULT: 1970-01-01
######### END_DATE [str]
# yyyy-mm-dd only include events before this date - DEFAULT: 2099-12-31

######### INCLUDE_ZEESCHUIMER_DATA [bool] # DEFAULT: true
######### INCLUDE_DONATION_DATA [bool] # DEFAULT: true

######### SELECTED_DONATIONS [List] # DEFAULT: []
# Sometimes we want to focus on certain donations. This allows you to do this. Leave empty to include all donations

######### DONATION_SAMPLE_FRAME [str] # DEFAULT: "off"
# Control if and how donations are sampled for this study
# off: no donations are included
# events: all events are included
# scraped: only events with scraped donations are included
# annotated: only events with annotated donations are included

# Donation sampling control - sampling are made at two levels - factors defining groups are defined in the variable schema
# The factors need to be exactly 2 and one need to be the Donation ID.
# If sampling frame is set to "off" you don't need to include this in your study definition
# First level - selection of events based on groups
######### MIN_EVENT_COUNT_REQUIRED_PER_AGG_GROUP [int] # groups w less than this number of events are excluded [DEFAULT: 10]
######### MAX_EVENT_COUNT_SELECTED_PER_AGG_GROUP [int] # groups w more than this number of events are downsampled to this number [DEFAULT: 100]
# Second level - selection of donations based on groups
######### MIN_GROUP_COUNT_REQUIRED_PER_DONATION [int] # donataions w less than this number of accepted groups are excluded [DEFAULT: 10]
######### MAX_GROUP_COUNT_SELECTED_PER_DONATION [int] # donataions w more than this number of accepted groups are downsampled to this number [DEFAULT: 100]
######### BALANCE_GROUP_SELECTION_OVER_TIME [bool] # not implemented yet

######### USER_ACCESS [List] # DEFAULT: ["all"]
# "all" - all users can access the study
# roles - only users with the specified roles can access the study




# ====================================================================================
# Study parameters: Definitions
# ====================================================================================


[baseline_only]
START_DATE = "2024-05-15"
END_DATE = "2024-07-15"
INCLUDE_ZEESCHUIMER_DATA = true
INCLUDE_DONATION_DATA = false
USER_ACCESS = ["all"]


[small_study_1]
START_DATE = "2024-05-01"
END_DATE = "2024-08-31"
INCLUDE_ZEESCHUIMER_DATA = true
INCLUDE_DONATION_DATA = true
SELECTED_DONATIONS = []

DONATION_SAMPLE_FRAME = "annotated"
MIN_EVENT_COUNT_REQUIRED_PER_AGG_GROUP = 30
MAX_EVENT_COUNT_SELECTED_PER_AGG_GROUP = 70
MIN_GROUP_COUNT_REQUIRED_PER_DONATION = 20
MAX_GROUP_COUNT_SELECTED_PER_DONATION = 40
BALANCE_GROUP_SELECTION_OVER_TIME = false
USER_ACCESS = ["all"]


[paper_one]
START_DATE = "2023-01-01"
END_DATE = "2025-12-31"
INCLUDE_ZEESCHUIMER_DATA = true
INCLUDE_DONATION_DATA = true
SELECTED_DONATIONS = []

DONATION_SAMPLE_FRAME = "events"
MIN_EVENT_COUNT_REQUIRED_PER_AGG_GROUP = 30
MAX_EVENT_COUNT_SELECTED_PER_AGG_GROUP = 70
MIN_GROUP_COUNT_REQUIRED_PER_DONATION = 20
MAX_GROUP_COUNT_SELECTED_PER_DONATION = 40
BALANCE_GROUP_SELECTION_OVER_TIME = false
USER_ACCESS = ["all"]


[chenglong]
START_DATE = "2025-04-15"
END_DATE = "2025-04-22"
INCLUDE_ZEESCHUIMER_DATA = false
INCLUDE_DONATION_DATA = true
SELECTED_DONATIONS = [
    'c7902493-838e-4602-a0c7-16b5ba8fba72',
    '84987fbf-b3d5-4f1d-9957-6ebad5ec6d18',
    'ae283f03-d5f7-40a4-beb3-b70e9c95aac2']
USER_ACCESS = ["researcher"]


[everything]
USER_ACCESS = ["admin"]

