# ====================================================================================
# Study parameters: Documentation
# ====================================================================================

# MIN_DURATION: minimum watch duration in seconds, set to 0 to include all events
# MIN_NUNIQUE_USERS: minimum number of unique users per video, set to 1 to include all events
# START_DATE & END_DATE: Only keep events between these date - parameters exist for DDPs and for Baseline
# SPECIAL_DONATIONS [List]: sometimes we want to focus on certain donations. This allows you to do this. It's a list of special donation IDs that are included in addition to the sampled events
# COL_MISSING_DATA_THRES [float]: some variables from the data enrichment have a lot of null values which are not useful and might as well be dropped. This parameter controls the threshold for dropping these columns if the fraction of missing data in a column is above this threshold, the column is dropped
# TIME_ZONE (e.g. "Australia/Brisbane"): timestamps in the data donation logs are reported in local timezones without information about which timezone it is. This parameter sets the assumed timezone for these. TODO: If we go international, this needs to be adjusted so that it can handle multiple timezones.
# AGG_GROUP_SIZE_PERCENTILE_LIMITS (e.g. [0.25,0.75]): percentile limits for the number of events in donation-dates groups, based on the median of all donation groups. The reasoning here is that I want 'average' TikTok dates. I want to avoid dates when the user has only watched very few videos or dates when they have watched thousands. 
# MIN_TIKTOK_DATES_WITHIN_LIMITS_PER_DONATION: I want donations where there are this many dates within the range defined by the previous parameter (AGG_GROUP_SIZE_PERCENTILE_LIMITS).
# N_SAMPLED_DATES_FROM_EACH_DONATION: how many dates to pick from each donation
# N_SAMPLED_EVENTS_FROM_EACH_AGG_GROUP: how many events to pick from each donation-date group


# ====================================================================================
# Study parameters: Here we go
# ====================================================================================


[baseline_only]
MIN_DURATION = 0 # minimum watch duration in seconds, set to 0 to include all events
MIN_NUNIQUE_USERS = 1 # minimum number of unique users per video, set to 1 to include all events
DDP_START_DATE = "2024-05-15" # only keep events after this date
DDP_END_DATE = "2024-07-15" # only keep events before this date
BASELINE_START_DATE = "2024-05-15" # only keep events after this date
BASELINE_END_DATE = "2024-07-15" # only keep events before this date
SPECIAL_DONATIONS = []
INCLUDE_ZEESCHUIMER_DATA = true
COL_MISSING_DATA_THRES = 0.5
TIME_ZONE = "Australia/Brisbane"
MIN_TIKTOK_DATES_WITHIN_LIMITS_PER_DONATION = 20
AGG_GROUP_SIZE_PERCENTILE_LIMITS = [0.25,0.75]
N_SAMPLED_DATES_FROM_EACH_DONATION = 35 #TODO: not really dynamic and flexible...
N_SAMPLED_EVENTS_FROM_EACH_AGG_GROUP = 38


[everything]
MIN_DURATION = 0 # minimum watch duration in seconds, set to 0 to include all events
MIN_NUNIQUE_USERS = 1 # minimum number of unique users per video, set to 1 to include all events
DDP_START_DATE = "2023-01-01" # only keep events after this date
DDP_END_DATE = "2025-12-31" # only keep events before this date
BASELINE_START_DATE = "2024-05-15" # only keep events after this date
BASELINE_END_DATE = "2024-07-15" # only keep events before this date
SPECIAL_DONATIONS = []
INCLUDE_ZEESCHUIMER_DATA = true
COL_MISSING_DATA_THRES = 0.5
TIME_ZONE = "Australia/Brisbane"
MIN_TIKTOK_DATES_WITHIN_LIMITS_PER_DONATION = 20
AGG_GROUP_SIZE_PERCENTILE_LIMITS = [0.25,0.75]
N_SAMPLED_DATES_FROM_EACH_DONATION = 35
N_SAMPLED_EVENTS_FROM_EACH_AGG_GROUP = 38


[compare_dd_w_baseline]
MIN_DURATION = 0 # minimum watch duration in seconds, set to 0 to include all events
MIN_NUNIQUE_USERS = 1 # minimum number of unique users per video, set to 1 to include all events
DDP_START_DATE = "2024-05-15" # only keep events after this date
DDP_END_DATE = "2024-07-15" # only keep events before this date
BASELINE_START_DATE = "2024-05-15" # only keep events after this date
BASELINE_END_DATE = "2024-07-15" # only keep events before this date
SPECIAL_DONATIONS = []
INCLUDE_ZEESCHUIMER_DATA = true
COL_MISSING_DATA_THRES = 0.5
TIME_ZONE = "Australia/Brisbane"
MIN_TIKTOK_DATES_WITHIN_LIMITS_PER_DONATION = 1
AGG_GROUP_SIZE_PERCENTILE_LIMITS = [0.25,0.75]
N_SAMPLED_DATES_FROM_EACH_DONATION = 35
N_SAMPLED_EVENTS_FROM_EACH_AGG_GROUP = 38


[chenglong]
MIN_DURATION = 0 # minimum watch duration in seconds, set to 0 to include all events
MIN_NUNIQUE_USERS = 1 # minimum number of unique users per video, set to 1 to include all events
DDP_START_DATE = "2025-04-15" # only keep events after this date
DDP_END_DATE = "2025-04-22" # only keep events before this date
BASELINE_START_DATE = "2024-05-15" # only keep events after this date
BASELINE_END_DATE = "2024-07-15" # only keep events before this date
SPECIAL_DONATIONS = [
    'c7902493-838e-4602-a0c7-16b5ba8fba72',
    '84987fbf-b3d5-4f1d-9957-6ebad5ec6d18',
    'ae283f03-d5f7-40a4-beb3-b70e9c95aac2']
INCLUDE_ZEESCHUIMER_DATA = false
COL_MISSING_DATA_THRES = 0.5
TIME_ZONE = "Australia/Brisbane"
MIN_TIKTOK_DATES_WITHIN_LIMITS_PER_DONATION = 20
AGG_GROUP_SIZE_PERCENTILE_LIMITS = [0.25,0.75]
N_SAMPLED_DATES_FROM_EACH_DONATION = 35
N_SAMPLED_EVENTS_FROM_EACH_AGG_GROUP = 38


[ica2026]
MIN_DURATION = 0 # minimum watch duration in seconds, set to 0 to include all events
MIN_NUNIQUE_USERS = 1 # minimum number of unique users per video, set to 1 to include all events
DDP_START_DATE = "2024-07-01" # only keep events after this date
DDP_END_DATE = "2024-12-31" # only keep events before this date
BASELINE_START_DATE = "2024-05-15" # only keep events after this date
BASELINE_END_DATE = "2024-07-15" # only keep events before this date
SPECIAL_DONATIONS = []
INCLUDE_ZEESCHUIMER_DATA = false
COL_MISSING_DATA_THRES = 0.5
TIME_ZONE = "Australia/Brisbane"
MIN_TIKTOK_DATES_WITHIN_LIMITS_PER_DONATION = 20
AGG_GROUP_SIZE_PERCENTILE_LIMITS = [0.25,0.75]
N_SAMPLED_DATES_FROM_EACH_DONATION = 35
N_SAMPLED_EVENTS_FROM_EACH_AGG_GROUP = 38

