"""Generate the fyp import-dependency matrix.

Scans ``fyp/*.py`` (and, post-restructure, ``fyp/**/*.py``) with the ``ast``
module and greps the rest of the repo for external importers. Emits a Markdown
report to stdout; the checked-in snapshot lives at ``docs/fyp-import-graph.md``.

That file is hand-written prose followed by this generated matrix, so redirecting
straight onto it destroys the prose. Refresh it by replacing only the tail, from
the ``GENERATED MATRIX BELOW`` marker down:

    python scripts/gen_import_graph.py > /tmp/matrix.md
"""

import argparse
import ast
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FYP = ROOT / "fyp"

EXTERNAL_SCAN_DIRS = ["web_interface", "tests", "scripts", "experiments"]
IMPORT_RE = re.compile(
    r"^\s*(?:from\s+(fyp(?:\.\w+)*)\s+import\s+(.+)|import\s+(fyp(?:\.\w+)*(?:\s+as\s+\w+)?))",
)





def fyp_modules() -> list[Path]:
    """Return all fyp module files, including subpackage members."""
    return sorted(p for p in FYP.rglob("*.py") if "__pycache__" not in p.parts)





def module_name(path: Path) -> str:
    """Dotted module name for a file under the project root."""
    rel = path.relative_to(ROOT).with_suffix("")
    return ".".join(rel.parts)





def internal_imports(path: Path) -> list[tuple[str, bool]]:
    """Return (imported fyp module, is_lazy) pairs found in one fyp file.

    is_lazy is True when the import statement sits inside a function or method
    body rather than at module level.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    found: list[tuple[str, bool]] = []

    module_level_nodes = set()
    for node in ast.iter_child_nodes(tree):
        module_level_nodes.add(id(node))

    for node in ast.walk(tree):
        target = None
        if isinstance(node, ast.ImportFrom) and node.module and node.module.startswith("fyp"):
            target = node.module
            # `from fyp import x` names submodules in the alias list
            if node.module == "fyp":
                for alias in node.names:
                    found.append((f"fyp.{alias.name}", id(node) not in module_level_nodes))
                continue
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("fyp."):
                    found.append((alias.name, id(node) not in module_level_nodes))
            continue
        if target:
            found.append((target, id(node) not in module_level_nodes))
    return found





def external_importers() -> dict[str, list[str]]:
    """Map each imported fyp path to the external files referencing it."""
    hits: dict[str, set[str]] = defaultdict(set)
    for d in EXTERNAL_SCAN_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for path in base.rglob("*.py"):
            if "__pycache__" in path.parts or ".fypenv" in str(path):
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except UnicodeDecodeError:
                continue
            for line in text.splitlines():
                m = IMPORT_RE.match(line)
                if not m:
                    continue
                mod = m.group(1) or (m.group(3) or "").split(" as ")[0].strip()
                if not mod or mod == "fyp":
                    if m.group(2):  # from fyp import a, b
                        for name in m.group(2).split(","):
                            token = name.strip().split(" as ")[0].strip("() ")
                            if token.isidentifier():
                                hits[f"fyp.{token}"].add(str(path.relative_to(ROOT)))
                    continue
                hits[mod].add(str(path.relative_to(ROOT)))
    return {k: sorted(v) for k, v in sorted(hits.items())}





def main() -> None:
    out = sys.stdout
    out.write("# fyp import-dependency matrix\n\n")
    out.write(
        "Generated by `scripts/gen_import_graph.py`; replaces everything below the\n"
        "`GENERATED MATRIX BELOW` marker in this file, never the whole file.\n\n"
    )

    out.write("## Internal adjacency (fyp -> fyp)\n\n")
    out.write("`(L)` marks a lazy (function-scoped) import.\n\n")
    for path in fyp_modules():
        name = module_name(path)
        edges = internal_imports(path)
        if not edges:
            continue
        seen: dict[str, bool] = {}
        for mod, lazy in edges:
            seen[mod] = seen.get(mod, True) and lazy
        rendered = ", ".join(
            f"{m.removeprefix('fyp.')}{' (L)' if lazy else ''}" for m, lazy in sorted(seen.items())
        )
        out.write(f"- **{name.removeprefix('fyp.')}** -> {rendered}\n")

    out.write("\n## External importers (web_interface / tests / scripts / experiments)\n\n")
    for mod, files in external_importers().items():
        out.write(f"- **{mod}**: {len(files)} file(s)\n")
        for f in files:
            out.write(f"  - {f}\n")





if __name__ == "__main__":
    argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    ).parse_args()
    main()
