"""docs/routes.md must match the live URL map.

The inventory is generated by ``scripts/gen_route_inventory.py``; this test
renders it the same way and compares, so a route change that forgets to
regenerate the doc fails the gate instead of drifting silently.
"""

import importlib.util
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _generator():
    path = PROJECT_ROOT / "scripts" / "gen_route_inventory.py"
    spec = importlib.util.spec_from_file_location("gen_route_inventory", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_routes_doc_matches_the_live_url_map():
    # The task-runner service registers only the internal blueprint; make sure
    # the full web UI registers before the app module is (first) imported.
    os.environ.pop("K_SERVICE", None)
    import web_interface.fyp_data_hub as hub

    gen = _generator()
    assert gen.ROUTES_DOC.read_text(encoding="utf-8") == gen.render(hub.app), (
        "docs/routes.md is stale — run: python scripts/gen_route_inventory.py"
    )
